# variable
@domain=localhost:3001
###
GET http://{{domain}}/quiz

###

POST  http://{{domain}}/quiz/create
Content-Type: application/json

{
    "title": "helloasdasdasd aaddsd asss",
    "description": "this is detailss",
    "isActive": 1
}

###
GET http://{{domain}}/quiz/1

###
GET http://{{domain}}/quiz/q?name=Hi

###
GET http://{{domain}}/quiz/ex/hello

###
GET http://{{domain}}/user/

###
POST  http://{{domain}}/user/create
Content-Type: application/json

{
    "username": "lijinx",
    "firstName": "Habor",
    "lastName": "TEST",
    "age": 102,
    "hobbys": [
        {
            "name": "test1",
            "frequency": "10"
        }
    ],
    "str_list": ["1","2"]

}

###
POST http://{{domain}}/user/hobbys
Content-Type: application/json

{
    "userId": "6380ab856bcd993328f03d1b",
  "hobbys": [
    {
      "id": "6384b5b549a80a2c50d9b30e",
      "name": "def",
      "frequency": "44444",
      "createDate": "2022-11-28T13:20:53.095Z",
      "updateDate": null
    },
    {
      "id": "6384b5c049a80a2c50d9b30f",
      "createDate": "2022-11-28T13:21:04.153Z",
      "name": "def",
      "frequency": "123"
    },
    {
      "name": "hello",
      "frequency": "20"
    }
  ]
}

###
POST http://{{domain}}/user/hobbys
Content-Type: application/json

{
    "userId": "6380ab856bcd993328f03d1b",
    "hobbys": [
        {
            "name": "def",
            "frequency": "2"
        }
    ]
}

###
POST http://{{domain}}/quiz/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="LeaveConfigFile"; filename="data0.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< ./data0.xlsx
------WebKitFormBoundary7MA4YWxkTrZu0gW--