# variable
@domain=localhost:3001
###
GET http://{{domain}}/quiz

###

POST  http://{{domain}}/quiz/create
Content-Type: application/json

{
    "title": "helloasdasdasd aaddsd asss",
    "description": "this is detailss",
    "isActive": 1
}

###
GET http://{{domain}}/quiz/1

###
GET http://{{domain}}/quiz/q?name=Hi

###
GET http://{{domain}}/quiz/ex/hello

###
GET http://{{domain}}/user/

###
POST  http://{{domain}}/user/create
Content-Type: application/json

{
    "username": "lijinx",
    "firstName": "Habor",
    "lastName": "TEST",
    "age": 102,
    "hobbys": [
        {
            "name": "test1",
            "frequency": "10"
        }
    ],
    "str_list": ["1","2"]

}

###
POST http://{{domain}}/user/hobbys
Content-Type: application/json

{
    "userId": "6380ab856bcd993328f03d1b",
  "hobbys": [
    {
      "id": "6380f249ef8c09e5fcf91ab7",
      "name": "abc5",
      "frequency": "1",
      "createDate": "2022-11-25T16:50:17.728Z",
      "updateDate": "2022-11-25T16:59:47.212Z"
    },
    {
      "id": "6380f255ec0aa6c0f4869e29",
      "name": "def6",
      "frequency": "2",
      "createDate": "2022-11-25T16:50:29.712Z"
    },
    {
      "name": "zxc8",
      "frequency": "3",
      "id": "6380f483de3da78224d7329e",
      "createDate": "2022-11-25T16:59:47.209Z"
    },
        {
      "name": "ttt",
      "frequency": "000"
    },
            {
      "name": "ttt",
      "frequency": "000"
    }
  ]
}

###
POST http://{{domain}}/user/hobbys
Content-Type: application/json

{
    "userId": "6380ab856bcd993328f03d1b",
    "hobbys": [
        {
            "name": "def",
            "frequency": "2"
        }
    ]
}